import os
import re
import json
from collections import Counter
from typing import Dict, List

def analyze_file_for_ai_signals(file_path: str) -> Dict:
    """Analyze a single file for AI generation signals."""
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception as e:
        return {"error": str(e)}
    
    signals = {
        "file_path": file_path,
        "ai_phrases_found": [],
        "naming_issues": [],
        "comment_patterns": [],
        "repetition_score": 0,
        "structure_score": 0,
        "ai_score": 0
    }
    
    # Check for AI-like phrases
    ai_phrases = [
        "generated by", "created by ai", "chatgpt", "claude",
        "as an ai", "as an ai assistant", "i am an ai",
        "i don't have access to", "i cannot provide",
        "as a large language model", "as an ai model",
        "i cannot browse", "i don't have browsing",
        "generated using ai", "ai generated"
    ]
    
    content_lower = content.lower()
    for phrase in ai_phrases:
        if phrase in content_lower:
            # Find all occurrences with context
            matches = re.finditer(re.escape(phrase), content_lower)
            for match in matches:
                start = max(0, match.start() - 50)
                end = min(len(content), match.end() + 50)
                context = content[start:end].strip()
                signals["ai_phrases_found"].append({
                    "phrase": phrase,
                    "context": context
                })
    
    # Check naming patterns
    naming_patterns = re.findall(r'(?:function|const|let|var|def|class)\s+([a-zA-Z_][a-zA-Z0-9_]*)', content)
    poor_names = []
    for name in naming_patterns:
        if len(name) < 4:
            poor_names.append(name)
        elif name in ['temp', 'data', 'item', 'value', 'result', 'output']:
            poor_names.append(name)
    
    if poor_names:
        signals["naming_issues"] = poor_names
    
    # Check comment patterns
    comments = re.findall(r'(?:#|//|/\*|<!--).*?(?:\*/|-->|$)', content, re.DOTALL)
    if comments:
        signals["comment_patterns"] = [comment.strip()[:100] + "..." if len(comment) > 100 else comment.strip() for comment in comments]
    
    # Check for repetition
    lines = [line.strip() for line in content.split('\n') if line.strip()]
    line_counter = Counter(lines)
    repeated_lines = [(line, count) for line, count in line_counter.items() if count > 1]
    if repeated_lines:
        signals["repetition_score"] = sum(count - 1 for line, count in repeated_lines)
        signals["repeated_lines"] = repeated_lines[:5]  # Show top 5
    
    # Check structure complexity
    indent_levels = re.findall(r'^\s+', content, re.MULTILINE)
    if indent_levels:
        avg_indent = sum(len(level) for level in indent_levels) / len(indent_levels)
        signals["structure_score"] = avg_indent
    
    # Calculate AI score
    score = 0
    if signals["ai_phrases_found"]:
        score += len(signals["ai_phrases_found"]) * 2
    if len(poor_names) > len(naming_patterns) * 0.5:
        score += 2
    if len(comments) > len(lines) * 0.3:  # Over-commented
        score += 2
    if signals["repetition_score"] > 5:
        score += 1.5
    avg_indent = signals.get("structure_score", 0)
    if avg_indent < 2:  # Too simple
        score += 1
    
    signals["ai_score"] = min(10, score)
    
    return signals

def scan_project_directory(project_path: str) -> List[Dict]:
    """Scan entire project directory for AI signals."""
    
    ai_signals = []
    
    # File extensions to analyze
    code_extensions = {'.js', '.jsx', '.ts', '.tsx', '.py', '.java', '.cpp', '.c', '.h', '.cs', '.php', '.rb', '.go', '.rs', '.swift', '.kt'}
    
    for root, dirs, files in os.walk(project_path):
        # Skip common non-code directories
        dirs[:] = [d for d in dirs if d not in ['.git', 'node_modules', '__pycache__', 'venv', 'env', 'dist', 'build']]
        
        for file in files:
            file_path = os.path.join(root, file)
            file_ext = os.path.splitext(file)[1].lower()
            
            if file_ext in code_extensions:
                signals = analyze_file_for_ai_signals(file_path)
                if signals.get("ai_score", 0) > 0 or signals.get("ai_phrases_found"):
                    ai_signals.append(signals)
    
    # Sort by AI score (highest first)
    ai_signals.sort(key=lambda x: x.get("ai_score", 0), reverse=True)
    
    return ai_signals

def main():
    """Main function to analyze the project."""
    
    print("🔍 AI Generation Detection Analysis")
    print("=" * 50)
    
    # Scan the current project directory
    project_path = "."
    ai_signals = scan_project_directory(project_path)
    
    if not ai_signals:
        print("✅ No AI generation signals detected in any files.")
        return
    
    print(f"📊 Found {len(ai_signals)} files with AI generation signals:\n")
    
    for i, signals in enumerate(ai_signals, 1):
        print(f"🔸 File {i}: {signals['file_path']}")
        print(f"   AI Score: {signals['ai_score']}/10")
        
        if signals.get("ai_phrases_found"):
            print(f"   🚨 AI Phrases Found ({len(signals['ai_phrases_found'])}):")
            for phrase_info in signals["ai_phrases_found"]:
                print(f"      • '{phrase_info['phrase']}' in: \"{phrase_info['context']}\"")
        
        if signals.get("naming_issues"):
            print(f"   📝 Naming Issues ({len(signals['naming_issues'])}): {signals['naming_issues'][:5]}")
        
        if signals.get("comment_patterns"):
            print(f"   💬 Comment Patterns ({len(signals['comment_patterns'])} comments)")
        
        if signals.get("repetition_score", 0) > 0:
            print(f"   🔄 Repetition Score: {signals['repetition_score']}")
            if "repeated_lines" in signals:
                print(f"      Examples: {signals['repeated_lines'][:3]}")
        
        if signals.get("structure_score", 0) > 0:
            print(f"   📐 Structure Score: {signals['structure_score']:.1f} (avg indent)")
        
        print()
    
    # Summary
    print("📋 Summary:")
    total_ai_phrases = sum(len(s.get("ai_phrases_found", [])) for s in ai_signals)
    high_score_files = [s for s in ai_signals if s["ai_score"] >= 5]
    
    print(f"   • Files with AI signals: {len(ai_signals)}")
    print(f"   • Total AI phrases found: {total_ai_phrases}")
    print(f"   • High-risk files (score ≥ 5): {len(high_score_files)}")
    
    if high_score_files:
        print(f"\n🚨 High-risk files:")
        for file in high_score_files:
            print(f"   • {file['file_path']} (score: {file['ai_score']})")

if __name__ == "__main__":
    main()
