import re
from collections import Counter

def analyze_specific_file(file_path):
    """Analyze one specific file in detail."""
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    print(f"🔍 Analyzing: {file_path}")
    print("=" * 50)
    
    # AI phrases check
    ai_phrases = [
        "generated by", "created by ai", "chatgpt", "claude",
        "as an ai", "as an ai assistant", "i am an ai",
        "i don't have access to", "i cannot provide",
        "as a large language model", "as an ai model",
        "i cannot browse", "i don't have browsing",
        "generated using ai", "ai generated", "gpt generated"
    ]
    
    content_lower = content.lower()
    found_phrases = []
    for phrase in ai_phrases:
        if phrase in content_lower:
            count = content_lower.count(phrase)
            found_phrases.append(f"{phrase} ({count}x)")
    
    if found_phrases:
        print(f"🚨 AI Phrases Found: {', '.join(found_phrases)}")
    else:
        print("✅ No AI phrases found")
    
    # Function naming analysis
    function_names = re.findall(r'function\s+([a-zA-Z_][a-zA-Z0-9_]*)', content)
    print(f"\n📝 Function Names ({len(function_names)}):")
    print(f"   {function_names[:10]}")  # Show first 10
    
    # Check for short/generic names
    short_names = [name for name in function_names if len(name) <= 3]
    generic_names = [name for name in function_names if name in ['temp', 'data', 'item', 'value', 'result', 'output', 'load', 'save', 'get', 'set']]
    
    if short_names:
        print(f"🟡 Short function names (≤3 chars): {short_names}")
    if generic_names:
        print(f"🟡 Generic function names: {generic_names}")
    
    # Variable naming analysis
    var_names = re.findall(r'(?:const|let|var)\s+([a-zA-Z_][a-zA-Z0-9_]*)', content)
    print(f"\n📊 Variable Names ({len(var_names)}):")
    print(f"   {var_names[:15]}")  # Show first 15
    
    short_vars = [name for name in var_names if len(name) <= 2]
    generic_vars = [name for name in var_names if name in ['i', 'j', 'k', 'x', 'y', 'z', 'data', 'item', 'value', 'temp', 'result']]
    
    if short_vars:
        print(f"🟡 Short variable names (≤2 chars): {short_vars}")
    if generic_vars:
        print(f"🟡 Generic variable names: {generic_vars}")
    
    # Repetition analysis
    lines = [line.strip() for line in content.split('\n') if line.strip()]
    line_counter = Counter(lines)
    repeated_lines = [(line, count) for line, count in line_counter.items() if count > 2]
    
    print(f"\n🔄 Repetition Analysis:")
    print(f"   Total lines: {len(lines)}")
    print(f"   Unique lines: {len(line_counter)}")
    print(f"   Lines repeated 3+ times: {len(repeated_lines)}")
    
    if repeated_lines:
        print(f"   Top repeated lines:")
        for line, count in repeated_lines[:5]:
            print(f"      ({count}x): {line[:80]}...")
    
    # Structure analysis
    indent_levels = re.findall(r'^\s+', content, re.MULTILINE)
    if indent_levels:
        avg_indent = sum(len(level) for level in indent_levels) / len(indent_levels)
        print(f"\n📐 Structure Analysis:")
        print(f"   Average indentation: {avg_indent:.1f} spaces")
        if avg_indent < 2:
            print("   🟡 Very simple structure (low indentation)")
        elif avg_indent > 8:
            print("   🟡 Very complex structure (high indentation)")
        else:
            print("   ✅ Normal structure complexity")
    
    # Calculate AI score based on the actual algorithm
    score = 0
    
    # AI phrases (highest weight)
    score += len(found_phrases) * 3
    
    # Poor naming
    if len(short_names) > len(function_names) * 0.3:
        score += 2
    elif len(short_names) > 0:
        score += 1
    
    # Generic names
    if len(generic_names) > len(function_names) * 0.5:
        score += 1
    
    # Repetition
    if len(repeated_lines) > 10:
        score += 2
    elif len(repeated_lines) > 5:
        score += 1
    
    # Simple structure
    if avg_indent < 2:
        score += 1
    
    print(f"\n📊 AI Detection Score: {score}/10")
    
    if score >= 7:
        level = "HIGH"
    elif score >= 4:
        level = "MEDIUM"
    else:
        level = "LOW"
    
    print(f"   Risk Level: {level}")
    
    return score

# Test one of the flagged files
file_path = r"c:\Users\RAM\OneDrive\Documents\Desktop\bvrit_hack\backend\storage\projects\02251f64-7c50-48a9-bec2-ba5aed7afad0\admin.js"
analyze_specific_file(file_path)
