import requests
import json

def debug_main_service_ai():
    """Debug main service AI detection integration"""
    print("🔍 Debugging Main Service AI Detection")
    print("=" * 60)
    
    # Test data with clear AI patterns
    test_data = {
        "projectId": "debug-main-ai",
        "language": "JavaScript",
        "metrics": {"qualityScore": 60, "structureScore": 55, "securityScore": 50},
        "importantFiles": [
            {
                "path": "ai_generated.js",
                "content": "// Generated by AI assistant\nconst data = [];\nfunction func() { console.log('As an AI assistant, I created this'); return data; }\n// This code was created using chatgpt\nconst temp = [];"
            }
        ],
        "readme": "Debug main service AI detection integration"
    }
    
    print(f"📊 Test Data:")
    print(f"   Files: {len(test_data['importantFiles'])}")
    print(f"   Content preview: {test_data['importantFiles'][0]['content'][:100]}...")
    
    try:
        print(f"\n🚀 Step 1: Call Main Service")
        response = requests.post("http://localhost:8002/evaluate", 
                            json=test_data, 
                            headers={"Content-Type": "application/json"}, 
                            timeout=60)
        
        print(f"   📡 Response Status: {response.status_code}")
        print(f"   📡 Response Headers: {dict(response.headers)}")
        
        if response.status_code == 200:
            try:
                result = response.json()
                print(f"   ✅ JSON Parse Success")
                
                # Step 2: Analyze main service response
                print(f"\n📋 Step 2: Analyze Main Service Response")
                print(f"   Top-level keys: {list(result.keys())}")
                
                # Check all fields
                for key in result.keys():
                    value = result[key]
                    if key == 'aiDetection':
                        print(f"   🤖 {key}: {type(value)} with {len(value) if isinstance(value, dict) else 'N/A'} keys")
                    elif key == 'summary':
                        print(f"   📝 {key}: {type(value)} = {value[:100] if value else 'None'}...")
                    else:
                        print(f"   📋 {key}: {type(value)}")
                
                # Focus on AI detection
                ai_detection = result.get('aiDetection', {})
                if ai_detection:
                    print(f"\n🤖 AI Detection Analysis:")
                    print(f"   Type: {type(ai_detection)}")
                    print(f"   Keys: {list(ai_detection.keys())}")
                    
                    level = ai_detection.get('level')
                    score = ai_detection.get('score')
                    confidence = ai_detection.get('confidence')
                    reasoning = ai_detection.get('reasoning')
                    
                    print(f"   🎯 Values:")
                    print(f"      Level: {level} (type: {type(level)})")
                    print(f"      Score: {score} (type: {type(score)})")
                    print(f"      Confidence: {confidence} (type: {type(confidence)})")
                    print(f"      Reasoning: {reasoning[:100] if reasoning else 'None'}...")
                    
                    # Check signals
                    signals = ai_detection.get('signals', {})
                    print(f"   📋 Signals: {type(signals)} with {len(signals)} keys")
                    
                    if signals:
                        for key, value in signals.items():
                            print(f"      {key}: {type(value)} = {str(value)[:80] if value else 'None'}...")
                    
                    # Check if AI was detected
                    print(f"\n🎯 AI Detection Result:")
                    if level == 'high' and score >= 8.0:
                        print(f"   🎉 AI DETECTED: High level with score {score}")
                        probability = 85 + min(score * 2, 15)
                        print(f"   📊 Frontend Should Display: {probability}% AI Generation")
                        print(f"   🏷️  Label: AI Generated")
                        print(f"   🎨 Color: Red (#ff4444)")
                        return True
                    elif level == 'medium' and score >= 5.0:
                        print(f"   ⚠️  AI DETECTED: Medium level with score {score}")
                        probability = 50 + (score * 5)
                        print(f"   📊 Frontend Should Display: {probability}% AI Generation")
                        print(f"   🏷️  Label: Likely AI")
                        print(f"   🎨 Color: Orange (#ff9800)")
                        return True
                    else:
                        print(f"   ❌ AI NOT DETECTED: Level {level}, Score {score}")
                        print(f"   📊 Frontend Should Display: Low AI Generation")
                        print(f"   🏷️  Label: Human Written")
                        print(f"   🎨 Color: Green (#28a745)")
                        return False
                else:
                    print(f"   ❌ No aiDetection field found")
                    print(f"   ❌ Available keys: {list(result.keys())}")
                    return False
                    
            except json.JSONDecodeError as e:
                print(f"   ❌ JSON Parse Error: {str(e)}")
                print(f"   📡 Raw Response: {response.text[:500]}...")
                return False
        else:
            print(f"   ❌ HTTP Error: {response.status_code}")
            print(f"   📡 Response: {response.text}")
            return False
            
    except Exception as e:
        print(f"\n❌ Request Error: {str(e)}")
        return False

if __name__ == "__main__":
    success = debug_main_service_ai()
    if success:
        print(f"\n🎉 Main Service AI Detection is working!")
        print(f"   Frontend should display: AI Generation Probability: 100%")
    else:
        print(f"\n⚠️  Main Service AI Detection has issues!")
