import requests
import json

def debug_ai_detection_response():
    """Debug AI detection service response in detail"""
    print("🔍 Debugging AI Detection Response")
    print("=" * 50)
    
    # Test data with clear AI patterns
    test_data = {
        "projectId": "debug-ai-response",
        "language": "JavaScript",
        "metrics": {"qualityScore": 60, "structureScore": 55, "securityScore": 50},
        "importantFiles": [
            {
                "path": "ai_generated.js",
                "content": "// Generated by AI assistant\nconst data = [];\nfunction func() { console.log('As an AI assistant, I created this'); return data; }\n// This code was created using chatgpt\nconst temp = [];"
            }
        ],
        "readme": "Debug AI detection response"
    }
    
    print(f"📊 Test Data:")
    print(f"   Content: {test_data['importantFiles'][0]['content'][:100]}...")
    
    try:
        # Call AI detection service
        response = requests.post("http://localhost:8003/detect", 
                            json=test_data, 
                            headers={"Content-Type": "application/json"}, 
                            timeout=60)
        
        print(f"\n📡 Raw Response Status: {response.status_code}")
        print(f"📡 Response Headers: {dict(response.headers)}")
        
        if response.status_code == 200:
            try:
                result = response.json()
                print(f"\n📡 Parsed JSON Response:")
                print(json.dumps(result, indent=2))
                
                ai_detection = result.get('aiDetection', {})
                print(f"\n🤖 AI Detection Breakdown:")
                print(f"   Level: {ai_detection.get('level')}")
                print(f"   Score: {ai_detection.get('score')}")
                print(f"   Confidence: {ai_detection.get('confidence')}")
                print(f"   Reasoning: {ai_detection.get('reasoning')}")
                
                signals = ai_detection.get('signals', {})
                print(f"\n📋 Signals:")
                print(f"   AI Phrases: {signals.get('ai_phrases')}")
                print(f"   Naming Issues: {signals.get('naming_issues')}")
                print(f"   Structure Patterns: {signals.get('structure_patterns')}")
                
                suspicious_files = ai_detection.get('suspicious_files', [])
                print(f"\n🚨 Suspicious Files: {len(suspicious_files)}")
                for file_info in suspicious_files:
                    print(f"   - {file_info.get('file')}: {file_info.get('issues')}")
                
                # Check if this looks correct
                level = ai_detection.get('level', '').lower()
                score = ai_detection.get('score', 0)
                ai_phrases = signals.get('ai_phrases', [])
                
                print(f"\n✅ Analysis:")
                print(f"   Level is '{level}' (should be high/medium/low)")
                print(f"   Score is {score} (should be > 5.0 for AI)")
                print(f"   AI phrases found: {len(ai_phrases)} (should be > 0)")
                
                if level == 'high' and score >= 8.0 and len(ai_phrases) > 0:
                    print(f"\n🎉 AI DETECTION WORKING CORRECTLY!")
                    print(f"   ✅ High level detected")
                    print(f"   ✅ High score detected ({score})")
                    print(f"   ✅ AI phrases detected ({len(ai_phrases)})")
                else:
                    print(f"\n⚠️  AI DETECTION NOT WORKING AS EXPECTED!")
                    print(f"   ❌ Level: {level} (expected: high)")
                    print(f"   ❌ Score: {score} (expected: >= 8.0)")
                    print(f"   ❌ AI phrases: {len(ai_phrases)} (expected: > 0)")
                
                return True
                
            except json.JSONDecodeError as e:
                print(f"\n❌ JSON Parse Error: {str(e)}")
                print(f"📡 Raw Response Text: {response.text[:500]}...")
                return False
        else:
            print(f"\n❌ HTTP Error: {response.status_code}")
            print(f"📡 Response Text: {response.text}")
            return False
            
    except Exception as e:
        print(f"\n❌ Request Error: {str(e)}")
        return False

if __name__ == "__main__":
    debug_ai_detection_response()
