import requests
import json

def debug_ai_service_internal():
    """Debug AI detection service internal processing"""
    print("🔍 Debugging AI Service Internal Processing")
    print("=" * 60)
    
    # Test data with clear AI patterns
    test_data = {
        "projectId": "debug-ai-service",
        "language": "JavaScript",
        "metrics": {"qualityScore": 60, "structureScore": 55, "securityScore": 50},
        "importantFiles": [
            {
                "path": "ai_generated.js",
                "content": "// Generated by AI assistant\nconst data = [];\nfunction func() { console.log('As an AI assistant, I created this'); return data; }\n// This code was created using chatgpt\nconst temp = [];"
            }
        ],
        "readme": "Debug AI service internal processing"
    }
    
    print(f"📊 Test Data:")
    print(f"   Files: {len(test_data['importantFiles'])}")
    print(f"   Content preview: {test_data['importantFiles'][0]['content'][:100]}...")
    
    try:
        # Step 1: Check service health
        print(f"\n🏥 Step 1: Check Service Health")
        health_response = requests.get("http://localhost:8003/health", timeout=10)
        if health_response.status_code == 200:
            health = health_response.json()
            print(f"   ✅ Service healthy: {health.get('status')}")
            print(f"   📋 Using: {health.get('api_key')} API key")
        else:
            print(f"   ❌ Service unhealthy: {health_response.status_code}")
            return False
        
        # Step 2: Call AI detection
        print(f"\n🤖 Step 2: Call AI Detection")
        response = requests.post("http://localhost:8003/detect", 
                            json=test_data, 
                            headers={"Content-Type": "application/json"}, 
                            timeout=60)
        
        print(f"   📡 Response Status: {response.status_code}")
        print(f"   📡 Response Headers: {dict(response.headers)}")
        
        if response.status_code == 200:
            try:
                result = response.json()
                print(f"   ✅ JSON Parse Success")
                
                # Step 3: Analyze response structure
                print(f"\n📋 Step 3: Analyze Response Structure")
                print(f"   Top-level keys: {list(result.keys())}")
                
                ai_detection = result.get('aiDetection', {})
                if ai_detection:
                    print(f"   ✅ aiDetection found: {type(ai_detection)}")
                    print(f"   ✅ aiDetection keys: {list(ai_detection.keys())}")
                    
                    level = ai_detection.get('level')
                    score = ai_detection.get('score')
                    confidence = ai_detection.get('confidence')
                    reasoning = ai_detection.get('reasoning')
                    
                    print(f"   🤖 AI Detection Values:")
                    print(f"      Level: {level} (type: {type(level)})")
                    print(f"      Score: {score} (type: {type(score)})")
                    print(f"      Confidence: {confidence} (type: {type(confidence)})")
                    print(f"      Reasoning: {reasoning[:100] if reasoning else 'None'}...")
                    
                    # Check signals
                    signals = ai_detection.get('signals', {})
                    print(f"   📋 Signals: {type(signals)} with {len(signals)} keys")
                    
                    if signals:
                        for key, value in signals.items():
                            print(f"      {key}: {type(value)} = {value}")
                            
                    # Check suspicious files
                    suspicious_files = ai_detection.get('suspicious_files', [])
                    print(f"   🚨 Suspicious Files: {len(suspicious_files)} items")
                    for file_info in suspicious_files:
                        print(f"      - {file_info.get('file')}: {file_info.get('issues')}")
                    
                    # Validate AI detection
                    print(f"\n🎯 AI Detection Validation:")
                    if level and score and confidence:
                        print(f"   ✅ Has required fields: level, score, confidence")
                        print(f"   ✅ Level: {level} (valid: {level in ['high', 'medium', 'low']})")
                        print(f"   ✅ Score: {score} (valid: 0-10)")
                        print(f"   ✅ Confidence: {confidence} (valid: 0-1)")
                        
                        # Check if AI was detected
                        if level == 'high' and score >= 8.0:
                            print(f"   🎉 AI DETECTED: High level with score {score}")
                            return True
                        elif level == 'medium' and score >= 5.0:
                            print(f"   ⚠️  AI DETECTED: Medium level with score {score}")
                            return True
                        else:
                            print(f"   ❌ AI NOT DETECTED: Level {level}, Score {score}")
                            return False
                    else:
                        print(f"   ❌ Missing required fields")
                        return False
                else:
                    print(f"   ❌ No aiDetection field found")
                    print(f"   ❌ Response: {json.dumps(result, indent=2)[:500]}...")
                    return False
                    
            except json.JSONDecodeError as e:
                print(f"   ❌ JSON Parse Error: {str(e)}")
                print(f"   📡 Raw Response: {response.text[:500]}...")
                return False
        else:
            print(f"   ❌ HTTP Error: {response.status_code}")
            print(f"   📡 Response: {response.text}")
            return False
            
    except Exception as e:
        print(f"\n❌ Request Error: {str(e)}")
        return False

if __name__ == "__main__":
    success = debug_ai_service_internal()
    if success:
        print(f"\n🎉 AI Detection Service is working correctly!")
    else:
        print(f"\n⚠️  AI Detection Service has issues!")
