import asyncio
import sys
import os

# Add ai_engine directory to path
sys.path.append(os.path.join(os.path.dirname(__file__), 'ai_engine'))

from ai_detection_service import AIDetectionService
from models import EvaluationInput, ImportantFile

async def debug_ai_detection():
    """Debug AI detection service"""
    print("🔍 Debugging AI Detection Service")
    print("=" * 50)
    
    try:
        # Initialize AI detection service
        service = AIDetectionService()
        print(f"✅ AI Detection Service initialized successfully")
        
        # Create test data
        files = [
            ImportantFile(
                path="test_ai.js",
                content="// Generated by AI assistant\nconst data = [];\nfunction func() { console.log('As an AI assistant, I created this'); return data; }"
            )
        ]
        
        input_data = EvaluationInput(
            projectId="debug-test",
            language="JavaScript",
            metrics={"qualityScore": 60},
            importantFiles=files,
            readme="Debug test"
        )
        
        print(f"📊 Created test data with clear AI patterns")
        
        # Test the AI detection directly
        result = await service.analyze_code_for_ai_signals(files, "debug-test")
        
        print(f"\n🤖 AI Detection Results:")
        print(f"   Level: {result.get('aiDetection', {}).get('level')}")
        print(f"   Score: {result.get('aiDetection', {}).get('score')}")
        print(f"   Reasoning: {result.get('aiDetection', {}).get('reasoning')}")
        
        signals = result.get('aiDetection', {}).get('signals', {})
        print(f"\n📋 Signals:")
        print(f"   AI Phrases: {signals.get('ai_phrases')}")
        print(f"   Naming Issues: {signals.get('naming_issues')}")
        
        return True
        
    except Exception as e:
        print(f"❌ Error: {str(e)}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    asyncio.run(debug_ai_detection())
