import os
import re
from collections import Counter

def check_file_for_ai_signs(file_path):
    """Check a single file for AI generation indicators."""
    
    try:
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
    except:
        return None
    
    # AI phrases that strongly indicate AI generation
    ai_phrases = [
        "generated by", "created by ai", "chatgpt", "claude",
        "as an ai", "as an ai assistant", "i am an ai",
        "i don't have access to", "i cannot provide",
        "as a large language model", "as an ai model",
        "i cannot browse", "i don't have browsing",
        "generated using ai", "ai generated", "gpt generated"
    ]
    
    findings = {
        "file": file_path,
        "ai_phrases": [],
        "suspicious_patterns": [],
        "ai_score": 0
    }
    
    content_lower = content.lower()
    
    # Check for AI phrases
    for phrase in ai_phrases:
        if phrase in content_lower:
            # Count occurrences
            count = content_lower.count(phrase)
            findings["ai_phrases"].append(f"{phrase} ({count}x)")
            findings["ai_score"] += count * 3  # Heavy weight for direct AI phrases
    
    # Check for suspicious patterns
    suspicious_patterns = [
        (r'function\s+[a-z]\s*\(', 'Single letter function names'),
        (r'const\s+[a-z]\s*=', 'Single letter variable names'),
        (r'\/\*\s*generated\s+by\s+ai', 'Comments mentioning AI generation'),
        (r'\/\/\s*generated\s+by\s+ai', 'Comments mentioning AI generation'),
        (r'function\s+func\d+\s*\(', 'Generic function names like func1, func2'),
        (r'class\s+Class\d+\s*', 'Generic class names like Class1, Class2'),
    ]
    
    for pattern, description in suspicious_patterns:
        matches = re.findall(pattern, content_lower)
        if matches:
            findings["suspicious_patterns"].append(f"{description}: {len(matches)}")
            findings["ai_score"] += len(matches)
    
    # Check for excessive repetition (common in AI-generated code)
    lines = [line.strip() for line in content.split('\n') if line.strip()]
    if len(lines) > 10:
        line_counter = Counter(lines)
        repeated_lines = [(line, count) for line, count in line_counter.items() if count > 2]
        if repeated_lines:
            findings["suspicious_patterns"].append(f"High repetition: {len(repeated_lines)} lines repeated 3+ times")
            findings["ai_score"] += min(3, len(repeated_lines))
    
    return findings if findings["ai_score"] > 0 else None

def main():
    print("🔍 Simple AI Generation Detection")
    print("=" * 40)
    
    # Key directories to check
    directories = [
        "ai_engine",
        "backend", 
        "analyzer_frontend/src",
        "analyzer",
        "sandbox"
    ]
    
    all_findings = []
    
    for directory in directories:
        if os.path.exists(directory):
            print(f"\n📁 Scanning {directory}/")
            for root, dirs, files in os.walk(directory):
                # Skip common non-code directories
                dirs[:] = [d for d in dirs if d not in ['node_modules', '__pycache__', '.git', 'dist', 'build']]
                
                for file in files:
                    if file.endswith(('.py', '.js', '.jsx', '.ts', '.tsx')):
                        file_path = os.path.join(root, file)
                        findings = check_file_for_ai_signs(file_path)
                        if findings:
                            all_findings.append(findings)
    
    # Sort by AI score (highest first)
    all_findings.sort(key=lambda x: x['ai_score'], reverse=True)
    
    if not all_findings:
        print("\n✅ No AI generation signals found in any files.")
        return
    
    print(f"\n🚨 Found {len(all_findings)} files with AI generation signals:\n")
    
    for i, finding in enumerate(all_findings, 1):
        print(f"{i}. 📄 {finding['file']}")
        print(f"   AI Score: {finding['ai_score']}")
        
        if finding['ai_phrases']:
            print(f"   🔴 AI Phrases: {', '.join(finding['ai_phrases'])}")
        
        if finding['suspicious_patterns']:
            print(f"   🟡 Suspicious Patterns: {', '.join(finding['suspicious_patterns'])}")
        
        print()
    
    # Summary
    high_risk = [f for f in all_findings if f['ai_score'] >= 5]
    print(f"📊 Summary:")
    print(f"   • Files with AI signals: {len(all_findings)}")
    print(f"   • High-risk files (score ≥ 5): {len(high_risk)}")
    
    if high_risk:
        print(f"\n🚨 High-risk files:")
        for f in high_risk:
            print(f"   • {f['file']} (score: {f['ai_score']})")

if __name__ == "__main__":
    main()
