import json
import logging
import re
import asyncio
from typing import Dict, Any, List
from collections import Counter

from config import Config
from llm_provider.groq_provider import GroqProvider

logger = logging.getLogger(__name__)

class AIDetectionService:
    """
    Dedicated AI detection service using secondary Groq API key.
    Provides enhanced AI generation detection for code analysis.
    """
    
    def __init__(self):
        # Use secondary API key for AI detection, fallback to primary if not available
        api_key = Config.GROQ_API_KEY_2 or Config.GROQ_API_KEY
        if not api_key:
            raise ValueError("No Groq API key available for AI detection")
        
        self.provider = GroqProvider(api_key, Config.MODEL_NAME)
        logger.info(f"AI Detection Service initialized with {'secondary' if Config.GROQ_API_KEY_2 else 'primary'} API key")
    
    async def analyze_code_for_ai_signals(self, files: List[Dict], project_id: str) -> Dict[str, Any]:
        """
        Analyze code files for AI generation signals using Groq API.
        """
        logger.info(f"Starting AI detection analysis for project {project_id}")
        
        # Prepare code content for analysis
        code_content = self._prepare_code_content(files)
        
        if not code_content.strip():
            logger.warning("No code content available for AI detection")
            return self._get_empty_detection_result(project_id)
        
        # Create AI detection prompt
        prompt = self._create_ai_detection_prompt(code_content, files)
        
        try:
            # Call Groq API for AI detection
            response = await self._call_ai_detection_api(prompt)
            return self._parse_ai_detection_response(response, project_id)
            
        except Exception as e:
            logger.error(f"AI detection failed: {str(e)}")
            return self._get_fallback_detection_result(project_id, str(e))
    
    def _prepare_code_content(self, files: List[Dict]) -> str:
        """Prepare code content for AI analysis."""
        content_parts = []
        
        for i, file in enumerate(files[:10]):  # Limit to first 10 files for token management
            # Handle both ImportantFile objects and dictionaries
            if hasattr(file, 'path') and hasattr(file, 'content'):
                file_path = file.path
                file_content = file.content
            elif isinstance(file, dict):
                file_path = file.get("path", f"file_{i}")
                file_content = file.get("content", "")
            else:
                # Fallback for other formats
                file_path = f"file_{i}"
                file_content = str(file)
            
            # Truncate very large files
            if len(file_content) > 2000:
                file_content = file_content[:2000] + "\n... [truncated for analysis]"
            
            content_parts.append(f"File {i+1}: {file_path}\n```\n{file_content}\n```\n")
        
        return "\n".join(content_parts)
    
    def _create_ai_detection_prompt(self, code_content: str, files: List[Dict]) -> str:
        """Create specialized prompt for AI generation detection."""
        
        return f"""You are an AI detection expert. Analyze the following code for signs of AI generation.

CRITICAL: Look specifically for these AI indicators:
1. AI phrases in comments: "generated by", "AI assistant", "chatgpt", "claude", "as an AI"
2. Generic naming: single letters (a, b, c), generic names (data, temp, item, value, func, class1)
3. Repetitive patterns: similar code structures repeated
4. Unusual consistency: perfect formatting, overly structured code

Code to analyze:
{code_content}

You MUST respond with valid JSON exactly in this format:
{{
    "aiDetection": {{
        "level": "high" if AI indicators found else "medium" if some indicators else "low",
        "score": 8.0 if many AI indicators else 5.0 if some indicators else 1.0,
        "confidence": 0.8,
        "reasoning": "Explain what AI indicators were found",
        "signals": {{
            "ai_phrases": ["list any AI-related phrases found"],
            "naming_issues": ["list any generic naming issues"],
            "structure_patterns": ["list any repetitive patterns"],
            "comment_analysis": "analysis of comment patterns",
            "complexity_analysis": "analysis of code complexity"
        }},
        "suspicious_files": [
            {{
                "file": "filename",
                "issues": ["issue1", "issue2"],
                "confidence": 0.8
            }}
        ]
    }},
    "fileCount": {len(files)},
    "analysisMethod": "groq_ai_detection"
}}

IMPORTANT: If you find AI phrases like "generated by" or "AI assistant", set level to "high" and score to 8.0+"""

    async def _call_ai_detection_api(self, prompt: str) -> Dict[str, Any]:
        """Call Groq API for AI detection with retry logic."""
        max_retries = 3
        
        for attempt in range(max_retries):
            try:
                logger.info(f"AI detection attempt {attempt + 1}/{max_retries}")
                
                response = await self.provider.evaluate_project(prompt)
                
                # Ensure response is dict
                if isinstance(response, str):
                    response = json.loads(response)
                
                logger.info("AI detection analysis completed successfully")
                return response
                
            except Exception as e:
                logger.warning(f"AI detection attempt {attempt + 1} failed: {str(e)}")
                
                # Check for rate limiting
                if "429" in str(e) or "Too Many Requests" in str(e):
                    if attempt < max_retries - 1:
                        delay = 10 * (attempt + 1)  # 10, 20, 30 seconds
                        logger.info(f"Rate limiting detected, waiting {delay} seconds...")
                        await asyncio.sleep(delay)
                        continue
                
                # Other errors
                if attempt < max_retries - 1:
                    await asyncio.sleep(2 ** attempt)  # 2, 4, 8 seconds
        
        raise Exception(f"AI detection failed after {max_retries} attempts")
    
    def _parse_ai_detection_response(self, response: Dict[str, Any], project_id: str) -> Dict[str, Any]:
        """Parse and validate AI detection response."""
        try:
            ai_detection = response.get("aiDetection", {})
            
            # Validate required fields
            if not ai_detection.get("level"):
                ai_detection["level"] = "low"
            if not isinstance(ai_detection.get("score"), (int, float)):
                ai_detection["score"] = 1.0
            if not isinstance(ai_detection.get("confidence"), (int, float)):
                ai_detection["confidence"] = 0.5
            
            # Ensure signals structure
            signals = ai_detection.get("signals", {})
            if not isinstance(signals, dict):
                signals = {}
                ai_detection["signals"] = signals
            
            # Default signal values
            signal_defaults = {
                "ai_phrases": [],
                "naming_issues": [],
                "structure_patterns": [],
                "comment_analysis": "No unusual patterns detected",
                "complexity_analysis": "Normal complexity"
            }
            
            for key, default_value in signal_defaults.items():
                if key not in signals:
                    signals[key] = default_value
            
            return {
                "projectId": project_id,
                "aiDetection": ai_detection,
                "fileCount": response.get("fileCount", 0),
                "analysisMethod": "groq_ai_detection",
                "timestamp": asyncio.get_event_loop().time()
            }
            
        except Exception as e:
            logger.error(f"Failed to parse AI detection response: {str(e)}")
            return self._get_fallback_detection_result(project_id, f"Parse error: {str(e)}")
    
    def _get_empty_detection_result(self, project_id: str) -> Dict[str, Any]:
        """Return result for empty/no code content."""
        return {
            "projectId": project_id,
            "aiDetection": {
                "level": "low",
                "score": 0.0,
                "confidence": 0.0,
                "reasoning": "No code content available for analysis",
                "signals": {
                    "ai_phrases": [],
                    "naming_issues": [],
                    "structure_patterns": [],
                    "comment_analysis": "No content to analyze",
                    "complexity_analysis": "No content to analyze"
                },
                "suspicious_files": []
            },
            "fileCount": 0,
            "analysisMethod": "groq_ai_detection",
            "timestamp": asyncio.get_event_loop().time()
        }
    
    def _get_fallback_detection_result(self, project_id: str, error_message: str) -> Dict[str, Any]:
        """Return fallback result when AI detection fails."""
        return {
            "projectId": project_id,
            "aiDetection": {
                "level": "low",
                "score": 1.0,
                "confidence": 0.2,
                "reasoning": f"AI detection analysis failed: {error_message}",
                "signals": {
                    "ai_phrases": [],
                    "naming_issues": [],
                    "structure_patterns": [],
                    "comment_analysis": "Analysis unavailable due to error",
                    "complexity_analysis": "Analysis unavailable due to error"
                },
                "suspicious_files": []
            },
            "fileCount": 0,
            "analysisMethod": "groq_ai_detection_fallback",
            "timestamp": asyncio.get_event_loop().time()
        }

# Singleton instance
_ai_detection_service = None

def get_ai_detection_service() -> AIDetectionService:
    """Get or create AI detection service instance."""
    global _ai_detection_service
    if _ai_detection_service is None:
        _ai_detection_service = AIDetectionService()
    return _ai_detection_service
