import { useState } from "react";
import { useLang } from "@/components/LangProvider";
import { Star, Download, MessageSquare } from "lucide-react";
import { toast } from "sonner";
import jsPDF from "jspdf";
import { mockReports } from "@/lib/mockData";

const Feedback = () => {
  const { t } = useLang();
  const [rating, setRating] = useState(0);
  const [hover, setHover] = useState(0);
  const [suggestion, setSuggestion] = useState("");
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = () => {
    setSubmitted(true);
    toast.success(t("submitFeedback") + " ✅");
  };

  // Trust score calculation (same logic as dashboard)
  const statusCounts = {
    solved: mockReports.filter((r) => r.status === "solved").length,
    total: mockReports.length,
  };
  const trustScore = Math.round((statusCounts.solved / statusCounts.total) * 100);

  const downloadComplaint = () => {
    const doc = new jsPDF();
    const report = mockReports[0];

    doc.setFontSize(18);
    doc.text("Official Complaint Letter", 20, 25);
    doc.setFontSize(11);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 40);
    doc.text("To: Municipal Corporation / Local Authority", 20, 50);
    doc.text("Subject: Civic Hazard Report — Immediate Action Required", 20, 65);

    doc.setFontSize(10);
    const body = [
      "",
      "Dear Sir/Madam,",
      "",
      "I am writing to formally report a civic hazard identified through the Civic Lens platform.",
      "",
      `GPS Coordinates: ${report.location.lat}, ${report.location.lng}`,
      `Location: ${report.address}`,
      `Hazard Category: ${report.category}`,
      "",
      "Health Risk Timeline (AI Analysis):",
      "  - 2 Days (Low Risk): Minor odor, basic filth, small pests.",
      "  - 5 Days (Medium Risk): Heavy odor, disease vectors breeding.",
      "  - 1 Week (High Risk): Severe infestation, potential outbreak.",
      "",
      "Environmental Impact:",
      "  - Carbon Footprint: 67%",
      "  - Soil Toxicity Index: 43%",
      "",
      `Community Trust Score: ${trustScore}%`,
      "",
      `Description: ${report.description}`,
      "",
      "I request immediate action to resolve this issue and prevent health risks",
      "to the local community.",
      "",
      "Sincerely,",
      "A Concerned Citizen via Civic Lens",
      "",
      "---",
      "Generated by Civic Lens — AI-Powered Civic Issue Reporting Platform",
    ];

    let y = 80;
    body.forEach((line) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(line, 20, y);
      y += 6;
    });

    doc.save("Civic_Lens_Complaint_Letter.pdf");
    toast.success("Complaint letter downloaded!");
  };

  return (
    <div className="min-h-screen py-8 px-4">
      <div className="container mx-auto max-w-2xl space-y-8">
        <div className="flex items-center gap-3">
          <MessageSquare className="h-7 w-7 text-secondary" />
          <h1 className="text-3xl font-bold gradient-text">{t("feedback")}</h1>
        </div>

        {/* Star Rating */}
        {!submitted ? (
          <div className="glass-card rounded-xl p-8 space-y-6">
            <div>
              <p className="text-foreground font-semibold mb-4">Rate your experience</p>
              <div className="flex gap-2">
                {[1, 2, 3, 4, 5].map((star) => (
                  <button
                    key={star}
                    onMouseEnter={() => setHover(star)}
                    onMouseLeave={() => setHover(0)}
                    onClick={() => setRating(star)}
                    className="transition-transform hover:scale-125"
                  >
                    <Star
                      className={`h-10 w-10 ${
                        star <= (hover || rating) ? "fill-warning text-warning" : "text-muted-foreground"
                      } transition-colors`}
                    />
                  </button>
                ))}
              </div>
            </div>

            <div>
              <label className="text-sm text-muted-foreground block mb-2">Suggestions</label>
              <textarea
                value={suggestion}
                onChange={(e) => setSuggestion(e.target.value)}
                className="w-full h-32 bg-muted border border-border rounded-lg p-3 text-foreground text-sm resize-none focus:outline-none focus:ring-2 focus:ring-primary"
                placeholder="Share your thoughts..."
              />
            </div>

            <div className="flex gap-3">
              <button
                onClick={handleSubmit}
                className="gradient-bg gradient-bg-hover px-6 py-3 rounded-lg font-semibold text-primary-foreground hover:scale-105 transition-all"
              >
                {t("submitFeedback")}
              </button>
              <button
                onClick={() => setSubmitted(true)}
                className="glass-card px-6 py-3 rounded-lg font-semibold text-muted-foreground hover:text-foreground transition-all"
              >
                {t("skip")} ⏩
              </button>
            </div>
          </div>
        ) : (
          <div className="glass-card rounded-xl p-8 text-center">
            <p className="text-lg font-semibold text-foreground mb-2">Thank you! 🎉</p>
            <p className="text-sm text-muted-foreground">Your feedback helps improve civic services.</p>
          </div>
        )}

        {/* Complaint Letter Download */}
        <div className="glass-card rounded-xl p-6">
          <h2 className="text-lg font-semibold text-foreground mb-3">Official Complaint Letter</h2>
          <p className="text-sm text-muted-foreground mb-4">
            Generate a formal document with GPS coordinates, hazard category, risk timeline, environmental scores, and Community Trust Score for submission to authorities.
          </p>
          <button
            onClick={downloadComplaint}
            className="gradient-bg gradient-bg-hover px-6 py-3 rounded-lg font-semibold text-primary-foreground flex items-center gap-2 hover:scale-105 transition-all"
          >
            <Download className="h-5 w-5" /> {t("downloadComplaint")} 📄
          </button>
        </div>
      </div>
    </div>
  );
};

export default Feedback;
